import { plainToInstance } from 'class-transformer';
import { validate } from 'class-validator';
import { RefreshTokenDto } from './refresh-token.dto.js';

describe('RefreshTokenDto', () => {
  it('accepts the exact base64url form generated by namou', async () => {
    const input = plainToInstance(RefreshTokenDto, {
      refreshToken: 'a'.repeat(43),
    });

    await expect(validate(input)).resolves.toHaveLength(0);
  });

  it.each(['short', ` ${'a'.repeat(43)}`, `${'a'.repeat(42)}+`])(
    'rejects malformed token %s',
    async (refreshToken) => {
      const input = plainToInstance(RefreshTokenDto, { refreshToken });

      const errors = await validate(input);

      expect(errors).toEqual(
        expect.arrayContaining([
          expect.objectContaining({ property: 'refreshToken' }),
        ]),
      );
    },
  );
});
